tests: add missing header for `difftime`
With GCC 14, which makes implicit function declarations an error by default:
```
TestReadMask.c: In function ‘ElapsedTime’:
TestReadMask.c:746:15: error: implicit declaration of function ‘difftime’ [-Wimplicit-function-declaration]
  746 |     ms = (int)difftime(end_time.tv_sec, start_time.tv_sec);
      |               ^~~~~~~~
TestReadMask.c:62:1: note: ‘difftime’ is defined in header ‘<time.h>’; this is probably fixable by adding ‘#include <time.h>’
   61 | #include <std.c>
  +++ |+#include <time.h>
   62 |
```

Fix the include guards and include <time.h> unconditionally (for difftime) and <string.h>
unconditionally too (for memcpy).

Signed-off-by: Sam James <sam@gentoo.org>